---
apiVersion: v1
kind: Namespace
metadata:
  name: lama-exps
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-spark-lama-data
spec:
  capacity:
    storage: '1000Gi'
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hdd
  mountOptions:
    - relatime
  hostPath:
    path: /mnt/ess_storage/DN_1/storage/sber_LAMA/kaggle_used_cars_dataset
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-lama-data
  namespace: lama-exps
spec:
  volumeName: pv-spark-lama-data
  storageClassName: local-hdd
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: '1000Gi'
