---
apiVersion: v1
kind: Pod
spec:
  volumes:
    - name: scripts-volume
      configMap:
        name: exp-test-scripts
  containers:
  - name: spark-kubernetes-driver
    imagePullPolicy: Always
    volumeMounts:
      - name: scripts-volume
        mountPath: /scripts
