---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-spark-lama-data
spec:
  capacity:
    storage: '1000Gi'
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hdd
  hostPath:
    path: /mnt/ess_storage/DN_1/storage/SLAMA/kaggle_used_cars_dataset
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-lama-data
spec:
  volumeName: pv-spark-lama-data
  storageClassName: local-hdd
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: '1000Gi'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mnt-nfs
spec:
  capacity:
    storage: '100Gi'
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  hostPath:
    path: /mnt/nfs
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mnt-nfs
spec:
  volumeName: pv-mnt-nfs
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: '100Gi'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-yarn-historyserver
spec:
  capacity:
    storage: '100Gi'
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hdd
  hostPath:
    path: /mnt/ess_storage/DN_1/storage/SLAMA/yarn-historyserver
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yarn-historyserver
spec:
  volumeName: pv-yarn-historyserver
  storageClassName: local-hdd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: '100Gi'
