version: '2'

services:
  spark-master:
    image: node2.bdcl:5000/spark-master-worker:3.2.1-py3.9
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    network_mode: "host"
  spark-worker-1:
    image: node2.bdcl:5000/spark-master-worker:3.2.1-py3.9
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://node3.bdcl:7077
      - SPARK_WORKER_MEMORY=110G
      - SPARK_WORKER_CORES=10
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    network_mode: "host"
    volumes:
      - /mnt/ess_storage/DN_1/storage/SLAMA/kaggle_used_cars_dataset:/opt/spark_data
      - /mnt/nfs/spark-lama-pipelines:/tmp/spark_results
    cpuset: "0-9"
#  spark-worker-2:
#    image: node2.bdcl:5000/spark-master-worker:3.2.1-py3.9
#    environment:
#      - SPARK_MODE=worker
#      - SPARK_MASTER_URL=spark://node3.bdcl:7077
#      - SPARK_WORKER_MEMORY=110G
#      - SPARK_WORKER_CORES=10
#      - SPARK_RPC_AUTHENTICATION_ENABLED=no
#      - SPARK_RPC_ENCRYPTION_ENABLED=no
#      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
#      - SPARK_SSL_ENABLED=no
#    network_mode: "host"
#    volumes:
#      - /mnt/ess_storage/DN_1/storage/SLAMA/kaggle_used_cars_dataset:/opt/spark_data
#      #      - /mnt/ess_storage/DN_1/storage/SLAMA/spark_checkpoints_ht_expt:/tmp/spark_checkpoints
#      - /mnt/nfs/spark-lama-pipelines:/tmp/spark_results
#    cpuset: "10-19"
  spark-submit:
    image: node2.bdcl:5000/spark-submitter:3.2.1-py3.9
    network_mode: "host"
    volumes:
      - /mnt/ess_storage/DN_1/storage/SLAMA/kaggle_used_cars_dataset:/opt/spark_data
#      - /mnt/ess_storage/DN_1/storage/SLAMA/spark_checkpoints_ht_expt:/tmp/spark_checkpoints
#      - /mnt/ess_storage/DN_1/storage/SLAMA/lightautoml_dist:/lightautoml_dist
#      - /mnt/ess_storage/DN_1/storage/SLAMA/lightautoml_jars:/lightautoml_jars
      - /mnt/nfs/spark-lama-pipelines:/tmp/spark_results
#      - /mnt/ess_storage/DN_1/storage/SLAMA/spark_cluster/ivy:/opt/bitnami/spark/ivy:z
#      - /mnt/ess_storage/DN_1/storage/SLAMA/spark_cluster/examples:/examples
    entrypoint: /bin/bash
    command: tail -f /dev/null
